# Generated by Django 4.1 on 2025-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('remarks', models.TextField()),
                ('total_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'grocery',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('remarks', models.TextField()),
                ('total_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'kitchen_stock',
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('total_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'snack_station',
            },
        ),
    ]
