# Generated by Django 5.2.1 on 2025-05-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
