# Generated by Django 5.2.1 on 2025-05-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_remove_history_description_history_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
