# Generated by Django 5.2.1 on 2025-06-08 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0005_grocery_total_cost_grocery_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
