# Generated by Django 5.2.1 on 2025-06-08 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0006_grocery_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
